### ISSUE TITLE
How to incrementally build the map?

### ISSUE THREAD

**Issue by LeeKeyu** [Dletta/conceptGraph#2]
Hi, thanks for your impressive contribution. I have a question regarding the code implementation. It seems that your code builds the semantic map in two separate steps - first extracting the segmentation masks and CLIP features of all the images, and second, incrementally fusing all the features.

Is it feasible to incrementally build the map from scratch by processing one image and feature fusion at a time? I am also curious about the hardware setting (especially GPU used) and the total time required to build a map of a room. 

Thank you in advance.

**Comment by Dletta** [comment]
@LeeKeyu  Edit: I didn't realize this was the conceptGraph repository. Apologies for the confusion.

What was implemented here does not have anything to do with room exploration.  This is a logic reasoning/inference engine over a graph knowledge base. Using Graph Homomorphism for reasonig according to Sowa's original ideas on Conceptual Graph reasoning. The semantic parts assume to have a set of schemata and a set of rules which define possible worlds. No computer vision is involved here.

I hope that clarifies your question.
